---
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install required packages
  apt:
    name:
      - apt-transport-https
    install_recommends: no
    state: present

- name: Add repository into /etc/apt/sources.list.d/kibana.list
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elasticsearch

- name: Install packages
  apt:
    name:
      - kibana
    install_recommends: no
    state: present

- name: Configure /etc/kibana/kibana.yml
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: kibana
    mode: 0660
  notify: restart kibana

- name: Enable and start service
  service:
    name: kibana
    state: started
    enabled: yes
